

.PHONY: all
all: 
	@echo "Nothing to make in this directory."

.PHONY: clean
clean:
	@echo "Nothing to clean in this directory."

.PHONY: run
run: 
	@echo "Nothing to run in this directory."


.PHONY: help
help:
	@echo "Nothing to make in this directory...stubbed make targets: ";
	@echo "  make help - shows this message";
	@echo "  make all - stubbed";
	@echo "  make run - stubbed";
	@echo "  make clean - stubbed"


