NETWORK_NAME = face-detection-retail-0004

.PHONY: all
all:
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)


.PHONY: deps
deps: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)
	

.PHONY: data
data:
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)
	

.PHONY: model_zoo
model_zoo:
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR) 


.PHONY: get_ir
get_ir:	
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)


.PHONY: compile_model
compile_model: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)
	
.PHONY: run
run: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)


.PHONY: run_py
run_py: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)


.PHONY: install-reqs
install-reqs: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)


.PHONY: uninstall-reqs
uninstall-reqs: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)
		

.PHONY: help
help:
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)

clean: 
	@echo $(YELLOW)'\n'${APP_NAME}": This network has moved to networks/face_detection_retail_0004"$(NOCOLOR)
