GREEN = '\033[1;32m'
YELLOW = '\033[1;33m'
NOCOLOR = '\033[0m'

.PHONY: all
all:
	@echo $(YELLOW)"\nThis content has been moved to the networks folder.\n"$(NOCOLOR)


.PHONY: help
help:
	@echo $(YELLOW)"\nThis content has been moved to the networks folder.\n"$(NOCOLOR)
