YELLOW = '\033[1;33m'
NOCOLOR = '\033[0m'

OLD_NETWORK_NAME = Inception_v3
NEW_NETWORK_NAME = inception_v3

.PHONY: all
all:
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)


.PHONY: deps
deps: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)
	

.PHONY: data
data:
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)
	

.PHONY: model_zoo
model_zoo:
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR) 


.PHONY: get_ir
get_ir:	
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)


.PHONY: compile_model
compile_model: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)
	
.PHONY: run
run: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)


.PHONY: run_py
run_py: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)


.PHONY: install-reqs
install-reqs: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)


.PHONY: uninstall-reqs
uninstall-reqs: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)
		

.PHONY: help
help:
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)

clean: 
	@echo $(YELLOW)'\n'${OLD_NETWORK_NAME}": This network has moved to networks/${NEW_NETWORK_NAME}"$(NOCOLOR)
